PGI.SB2.App/Controllers/HomeController.cs
using log4net;
using log4net.Config;
using PGI.SB2.App.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PGI.SB2.App.Controllers
{
    [SessionAuthorize]
    public class HomeController : Controller
    {
        private static readonly ILog log = LogManager.GetLogger(typeof(HomeController));

        public HomeController()
        {
            XmlConfigurator.Configure();
        }

        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PGI.SB2.App/Controllers/PluginController.cs
using PGI.SB2.App.Models;
using PGI.SB2.App.Utilities;
using PGI.SB2.SDK;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PGI.SB2.App.Controllers
{
    [SessionAuthorize]
    public class PluginController : Controller
    {
        //
        // GET: /Plugin/

        public ActionResult Index()
        {
            ListPluginsModel model = new ListPluginsModel();

            try
            {
                ReadSession session = ViewBag.Session;
                if (session != null)
                {

                    ListPluginsRequest request = new ListPluginsRequest()
                    {
                        BaseURL = System.Configuration.ConfigurationManager.AppSettings["APIBaseURL"],
                        AccessKey = session.UserName,
                        SecretKey = session.SecretKey
                    };

                    ListPluginsResponse response = Client.ListPlugins(request);
                    model.Plugins = response.Detail.Plugins;
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View(model);
        }

    }
}

PGI.SB2.App/Controllers/TestController.cs
using PGI.SB2.App.Utilities;
using PGI.SB2.Core;
using PGI.SB2.SDK;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PGI.SB2.App.Controllers
{
    [SessionAuthorize]
    public class TestController : Controller
    {
        //
        // GET: /Test/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create100()
        {
            string appPath = System.Web.Hosting.HostingEnvironment.MapPath(System.Web.HttpRuntime.AppDomainAppVirtualPath);

            ReadSession session = ViewBag.Session;

            for (int i = 301; i < 600; i++)
            {
                Random rnd1 = new Random(System.Environment.TickCount);

                CreateAssetRequest request = new CreateAssetRequest()
                {
                    BaseURL = System.Configuration.ConfigurationManager.AppSettings["APIBaseURL"],
                    AccessKey = session.UserName,
                    SecretKey = session.SecretKey
                };

                request.Asset = new CreateAsset();

                request.Asset.CompanyID = "Company ABC";
                request.Asset.CompanyName = "Test Company";
                request.Asset.ClientID = rnd1.Next(100000, 999999).ToString();
                request.Asset.ModeratorName = "Test Moderator";
                request.Asset.ModeratorEmail = "test@test.com";
                request.Asset.ConferenceID = rnd1.Next(100000, 999999).ToString();
                request.Asset.ConferenceName = "Conference #" + rnd1.Next(100000, 999999).ToString();
                request.Asset.ConferenceLink = rnd1.Next(100000, 999999).ToString();
                request.Asset.EventStartUTC = System.DateTime.Now.ToUniversalTime().ToString(Constants.UTC_FORMAT);
                request.Asset.EventEndUTC = System.DateTime.Now.AddHours(1).ToUniversalTime().ToString(Constants.UTC_FORMAT);
                request.Asset.RegionName = "us-west-2";
                request.Asset.Notes = "Test Notes for Asset #" + i.ToString();

                int number = rnd1.Next(1, 8);
                switch (number)
                {
                    case 1:
                        request.Asset.Name = "Bond_" + i.ToString();
                        request.FileName = "bond.wav";
                        request.InputStream = new FileStream(appPath + "\\Content\\Tests\\wav\\bond.wav", FileMode.Open, FileAccess.Read);
                        break;
                    case 2:
                        request.Asset.Name = "Booboo_" + i.ToString();
                        request.FileName = "booboo.wav";
                        request.InputStream = new FileStream(appPath + "\\Content\\Tests\\wav\\booboo.wav", FileMode.Open, FileAccess.Read);
                        break;
                    case 3:
                        request.Asset.Name = "GoodEvening_" + i.ToString();
                        request.FileName = "goodevening.wav";
                        request.InputStream = new FileStream(appPath + "\\Content\\Tests\\wav\\goodevening.wav", FileMode.Open, FileAccess.Read);
                        break;
                    case 4:
                        request.Asset.Name = "Terminator_" + i.ToString();
                        request.FileName = "terminator.wav";
                        request.InputStream = new FileStream(appPath + "\\Content\\Tests\\wav\\terminator.wav", FileMode.Open, FileAccess.Read);
                        break;
                    case 5:
                        request.Asset.Name = "Koala_" + i.ToString();
                        request.FileName = "Koala.jpg";
                        request.InputStream = new FileStream(appPath + "\\Content\\Tests\\jpg\\Koala.jpg", FileMode.Open, FileAccess.Read);
                        break;
                    case 6:
                        request.Asset.Name = "Lighthouse_" + i.ToString();
                        request.FileName = "Lighthouse.jpg";
                        request.InputStream = new FileStream(appPath + "\\Content\\Tests\\jpg\\Lighthouse.jpg", FileMode.Open, FileAccess.Read);
                        break;
                    case 7:
                        request.Asset.Name = "Penguins_" + i.ToString();
                        request.FileName = "Penguins.jpg";
                        request.InputStream = new FileStream(appPath + "\\Content\\Tests\\jpg\\Penguins.jpg", FileMode.Open, FileAccess.Read);
                        break;
                    case 8:
                        request.Asset.Name = "Tulips_" + i.ToString();
                        request.FileName = "Tulips.jpg";
                        request.InputStream = new FileStream(appPath + "\\Content\\Tests\\jpg\\Tulips.jpg", FileMode.Open, FileAccess.Read);
                        break;
                }


                CreateAssetResponse response = Client.CreateAsset(request);
            }

            return RedirectToAction("Index");
        }
    }
}

PGI.SB2.App/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

PGI.SB2.App/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

PGI.SB2.App/Views/Home/Index.cshtml
@using PGI.SB2.App.Utilities
@{
    ViewBag.Title = ContentFactory.GetContent("application_name");
}

<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span class="glyphicon glyphicon-bookmark"></span> @ContentFactory.GetContent("shortcuts")
                </h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <a href="@Url.Action("Index", "Asset")" class="btn btn-danger btn-lg btn-block" role="button"><span class="glyphicon glyphicon-search"></span> @ContentFactory.GetContent("search_existing_asset")</a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <a href="@Url.Action("Upload", "Asset")" class="btn btn-warning btn-lg btn-block" role="button"><span class="glyphicon glyphicon-cloud-upload"></span> @ContentFactory.GetContent("upload_new_asset")</a>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <a href="@Url.Action("Index", "Test")" class="btn btn-success btn-lg btn-block" role="button"><span class="glyphicon glyphicon-cloud-upload"></span> @ContentFactory.GetContent("tests")</a>
                        </div>
                    </div>
                </div>


                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <a href="@Url.Action("Index", "Plugin")" class="btn btn-primary btn-lg btn-block" role="button"><span class="glyphicon glyphicon-signal"></span> @ContentFactory.GetContent("plugins")</a>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>